version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_PAYFAST_MERCHANT_ID=${NEXT_PUBLIC_PAYFAST_MERCHANT_ID}
      - NEXT_PUBLIC_PAYFAST_MERCHANT_KEY=${NEXT_PUBLIC_PAYFAST_MERCHANT_KEY}
      - NEXT_PUBLIC_PAYFAST_PASSPHRASE=${NEXT_PUBLIC_PAYFAST_PASSPHRASE}
      - NEXT_PUBLIC_PAYFAST_SANDBOX=${NEXT_PUBLIC_PAYFAST_SANDBOX:-true}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_PAYFAST_MERCHANT_ID=${NEXT_PUBLIC_PAYFAST_MERCHANT_ID}
      - NEXT_PUBLIC_PAYFAST_MERCHANT_KEY=${NEXT_PUBLIC_PAYFAST_MERCHANT_KEY}
      - NEXT_PUBLIC_PAYFAST_PASSPHRASE=${NEXT_PUBLIC_PAYFAST_PASSPHRASE}
      - NEXT_PUBLIC_PAYFAST_SANDBOX=${NEXT_PUBLIC_PAYFAST_SANDBOX:-true}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev

